markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

host: wkliang.github.com

custom:
    category:
        thinking: 思考
        reading: 閱讀
        note: 筆記
    categories:
      - name:  thinking
        title: 思考

      - name:  reading
        title: 閱讀

      - name:  note
        title: 筆記

meta:
    authors:
      - name: wkliang
        email: wenkui.liang@gmail.com
        gravatar: none

    gravatar:
        base: http://www.gravatar.com/avatar/
        param: ?s=
